# fastqc-test.sub 
# HTCondor submit file for fastqc with docker container for performing
# fastqc, trimming, and fastqc post-trimming
# Run: condor_submit fastqc-test.sub

# Line added to ensure node has access to staging
Requirements = (Target.hasCHTCStaging == true)

# Provide HTCondor with the name of the Docker container
container_image = docker://jespina/chtc-qc:dev
universe = container

# Test fastq file
fastq = SA1-IgG-240801_S523_L008_R1_001.fastq.gz 

# Specify executable and arguments
# $(fastq) is name of test file
executable = fastqc-test.sh
arguments = $(fastq)
   		
# specify name of the log, standard error, and standard output files 
# $(Cluster) represents queue number assigned to this set of jobs at the time of submission
# $(Process) is integer number for each job starting from "0"
log = $(fastq)_$(Cluster)_$(Process).log
error = $(fastq)_$(Cluster)_$(Process).err
output = $(fastq)_$(Cluster)_$(Process).out
   
# transfer files in/out of /home/{net-id}/
# transfer output files on exit from compute node
should_transfer_files = YES
transfer_input_files = 
when_to_transfer_output = ON_EXIT
   
# memory, disk, and cpu requirements
request_cpus = 1
request_memory = 8GB
request_disk = 5GB
   
# Tell HTCondor to run 1 instance of our job:
queue 1
###END
