# pe-trim.sub 
# HTCondor submit file with docker container for performing
# fastqc, trimming, and fastqc post-trimming
# Run: condor_submit pe-trim.sub

# Line added to ensure node has access to staging
Requirements = (Target.hasCHTCStaging == true)

# Provide HTCondor with the name of the Docker container
container_image = docker://jespina/chtc-qc:dev
universe = container

# Test fastq file
fastq_1 = SA1-IgG-240801_S523_L008_R1_001.fastq.gz 
fastq_2 = SA1-IgG-240801_S523_L008_R2_001.fastq.gz

# Specify executable and arguments
# $(fastq_1) and $(fastq_2) are names of test files
executable = pe-trim.sh
arguments = $(fastq_1) $(fastq_2)
   		
# specify name of the log, standard error, and standard output files 
# $(Cluster) represents queue number assigned to this set of jobs at the time of submission
# $(Process) is integer number for each job starting from "0"
log = $(fastq_1)_$(Cluster)_$(Process).log
error = $(fastq_1)_$(Cluster)_$(Process).err
output = $(fastq_1)_$(Cluster)_$(Process).out
   
# transfer files in/out of /home/{net-id}/
# transfer output files on exit from compute node
should_transfer_files = YES
transfer_input_files = 
when_to_transfer_output = ON_EXIT
   
# memory, disk, and cpu requirements
request_cpus = 4
request_memory = 16GB
request_disk = 16GB
   
# Tell HTCondor to run 1 instance of our job:
queue 1
###END
