# pe-trim.sub 
# HTCondor submit file with docker container for performing
# fastqc, trimming, and fastqc post-trimming
# Run: condor_submit pe-trim_multi.sub

# Line added to ensure node has access to staging
Requirements = (Target.hasCHTCStaging == true)

# Provide HTCondor with the name of the Docker container
container_image = docker://jespina/chtc-trim:1.0
universe = container

# Specify executable and arguments
# $(fastq1) and $(fastq2) are paired-end read files queued from a samplesheet.txt file
# NOTE - queueing over list does not seem to work if variable contains special character
executable = pe-trim.sh
arguments = $(samplename) $(fastq1) $(fastq2)
   		
# specify name of the log, standard error, and standard output files 
# $(Cluster) represents queue number assigned to this set of jobs at the time of submission
# $(Process) is integer number for each job starting from "0"
log = $(samplename)_$(Cluster)_$(Process).log
error = $(samplename)_$(Cluster)_$(Process).err
output = $(samplename)_$(Cluster)_$(Process).out
   
# transfer files in/out of /home/{net-id}/
# transfer output files on exit from compute node
should_transfer_files = YES
transfer_input_files = 
when_to_transfer_output = ON_EXIT
   
# memory, disk, and cpu requirements
request_cpus = 4
request_memory = 16GB
request_disk = 16GB
   
# Tell HTCondor to queue over a samplesheet.txt file
queue samplename,fastq1,fastq2 from samplesheet.txt
###END
